### ISSUE TITLE
Evaluation on voxforge

### ISSUE THREAD

**Issue by Huiimin5** [nttcslab/byol-a#15] opened 2022-10-14 06:51 UTC
Hi,

Thank you so much for your contribution. This works is very interesting and your code is easy for me to follow. But one of the downstream dataset, voxforge is missing from the preprocess_ds.py. Could you please release the code for that dataset, too?

Thank you again for your time.

Best regards

**Comment by daisukelab** [comment] 2022-10-14 07:36
Hi @Huiimin5,
Thank you for your comments and attention.

I'm afraid, but we have moved on to the new evaluation package [EVAR](https://github.com/nttcslab/eval-audio-repr).
Could you refer to it, please?
It should provide complete information for evaluating various audio representations.

You might first visit the [V2 page](https://github.com/nttcslab/byol-a/tree/master/v2) of the BYOL-A for your quick start.

We are sorry that it's not a quick solution for you. But I'm sure this is an answer to provide in-depth materials.

**Comment by Huiimin5** [comment] 2022-10-14 08:37
Hi,
Thank you so much for your quick response. It is a very nice platform to evaluate audio representations. I notice that the metadata of voxfurge dataset is provided here: https://raw.githubusercontent.com/nttcslab/eval-audio-repr/main/evar/metadata/voxforge.csv. Does itmean that with this metadata and using convert_wav() to preprocess the dataset downloaded from the script here: https://github.com/nttcslab/eval-audio-repr/blob/main/Preparing-datasets.md#voxforge, I should be able to reproduce the results reported in the first versoin of BYOL-A?

**Comment by Huiimin5** [comment] 2022-10-14 09:42
OKOK, many thanks.
I will also try to reproduce and let you know the results.
By the way, could you please also release code pieces for SPCV2/12?
Thank you again for your time.

**Comment by daisukelab** [comment] 2022-10-14 10:46
For the SPCV2/12, we used TFDS.
https://www.tensorflow.org/datasets/catalog/speech_commands
And we are sorry that we evaluated with old code, which is not compatible with the current code. Honestly, we need to rewrite it if we are going to make it open.

We stopped using 12 class version of the Speech Commands because the splits are not formally defined (or, I should say, it is unclear), thus, less reproducible.

**Comment by daisukelab** [comment] 2022-10-14 13:58
That's the problem. We totally relied on the TFDS metadata. No CSV...
I am sorry that we cannot help with it.

**Comment by daisukelab** [comment] 2022-10-25 01:39
@Huiimin5 Thank you for waiting. (Though I guess it's too late for your ICASSP submission)

### Quick answers
- Is the [voxforge.csv](https://raw.githubusercontent.com/nttcslab/eval-audio-repr/main/evar/metadata/voxforge.csv) compatible with the first version of BYOL-A? No. I confirmed that we have used TFDS for testing on Voxforge.
- Then, what is the best thing we can use for current and future studies? It'd be the [voxforge.csv](https://raw.githubusercontent.com/nttcslab/eval-audio-repr/main/evar/metadata/voxforge.csv) from [EVAR](https://github.com/nttcslab/eval-audio-repr), or, please use the EVAR for your evaluation.

As far as using the EVAR, we can reproduce closer results on the [newer BYOL-A paper](https://arxiv.org/abs/2204.07402) (It was accepted, and will be published soon in a journal).

### What I could confirm so far

I confirmed closer, but better results than the first BYOL-A paper.

> python lineareval.py config/byola.yaml voxforge -> resulted in 0.91817, 0.91874, 0.91867, ...
> python lineareval.py config/byola.yaml vc1    --> resulted in about 0.424

### It's the same situation with the VoxCeleb1
 
I confirmed that we have also used TFDS with VoxCeleb1.

I hope these answer your questions. If you need to ask any other things, please feel free to ask.

**Comment by daisukelab** [comment] 2022-11-02 11:03
@Huiimin5  Hi, I'm closing this issue. But you can re-open whatever you wish to ask.
Thanks for your questions.

**Closed by daisukelab** 2022-11-02 11:03 UTC
